
import Script from "next/script"; // ✅ add this import at the top
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserAuthProvider from "./provider/UserAuthProvider";
import { ToastContainer } from "react-toastify";
import ListingProvider from "./provider/ListingProvider";
import BookingProvider from "./provider/BookingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arbnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer/>
             <UserAuthProvider>
            <ListingProvider>
          <BookingProvider>
        {children}
        </BookingProvider>
        </ListingProvider>
        </UserAuthProvider>
      </body>
    </html>
  );
}
